%structure of when each recording start and its name

function [recording_intervals]=extract_recordings_folder_start(basepath,session,original_dat_name,xml_file)
%function to extract what timepoint each folder start and its name

filePaths = fullfile(basepath,session.recording_folders,original_dat_name);
total_ch=xml_file.nChannels;
sr=xml_file.SampleRate;
for a = 1:length(filePaths)
   d = dir(filePaths{a});
   datSize_s(a) = d.bytes/total_ch/sr/2;
end

recordingIntervals = cumsum(datSize_s); %in s

recording_intervals.folders_name = session.recording_folders;
recording_intervals.folders_name_info = 'recording sessions original folders name, before being concatenated';
recording_intervals.stop_times = recordingIntervals;
recording_intervals.stop_times_info = 'recording sessions stop times on the concatenated file, units are in seconds';
aux = which('extract_recordings_folder_start');
recording_intervals.script_info = ['file generated by the function extract_recordings_folder_start at ' aux];
